notifications:
 email: false

language: python

python: 3.6

install:

 - pip install -r requirements.txt

script:

 - errors=`find . -name "*.py" -exec flake8 --max-line-length=120 \;`

 - |

  if [ -z "$errors" ] then

   true

  else

   echo "$errors"

   false

  fi
